config/routes.rb
Anabol::Application.routes.draw do

  resources :versions,  :path => "/verziok"#, :only => [:edit, :update, :index, :new, :creae],
  resources :meta_reports

  devise_scope :user do
    get '/felhasznalok/auth/:provider' => 'users/omniauth_callbacks#passthru'
    get "/belepes" => "devise/sessions#new"
    get "/regisztracio" => "devise/registrations#new"
    match "/kilepes" => "devise/sessions#destroy"
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/meta", to: "static_pages#meta"
  get "/adatvedelem", to: "static_pages#adatvedelem"
  get "/feltetelek", to: "static_pages#feltetelek"
  get "/users", to: "static_pages#users"

  Inboxes::Engine.routes.draw do
    resources :discussions, :except => :edit, :module => :inboxes do
      resources :messages, :only => [:create, :index]
      resources :speakers, :only => [:create, :destroy]
      member do
        post 'leave'
      end
    end
  end

  resources :relationships, only: [:create, :destroy]
  root :to => "static_pages#home"

  get 'kereses' => 'profiles#index'

  resources :profiles, :only => [:show, :edit, :update, :destroy, :index], :path => "/profil" do
     resources :sizes, :path => "meres"
     resources :workouts, :path => "edzes"
     resources :photos, :path => "kepek"
    member do
      get :following, :followers
    end
  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :name, :user_id,:date_of_birth, :nem2, :magassag, :varos, :gym, :image, :real_name, :user_name, :sport, :description, :private, :cover_image

  validates_uniqueness_of :slug

  after_save :set_my_name

  extend FriendlyId
  friendly_id :user_name, use: :slugged
  belongs_to :user

  has_many :sizes, :dependent => :destroy
  has_many :workouts, :dependent => :destroy
  has_many :meta_reports
  has_many :photos, :dependent => :destroy

  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_profiles, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  
  mount_uploader :image, ImageUploader
  mount_uploader :cover_image, ImageUploader

  def following?(other_profile)
    relationships.find_by_followed_id(other_profile.id)
  end

  def follow!(other_profile)
    relationships.create!(followed_id: other_profile.id)
  end

  def unfollow!(other_profile)
    relationships.find_by_followed_id(other_profile.id).destroy
  end

  def set_my_name
    @user = User.find_by_id(user_id)
    @user.uname = user_name
    @user.save
  end

  def self.searchable_language
    'hungarian'
  end

  def self.text_search(query)
    if query.present?
      search(query)
    else
      scoped
    end
  end
end

app/controllers/profiles_controller.rb
# coding: utf-8
class ProfilesController < ApplicationController
  
  before_filter :get_user

  load_and_authorize_resource

  def index
    @profiles = (Profile.text_search(params[:query])).order("followers Desc").first(50)
  end

  def show
  	@profile = Profile.find(params[:id])
    @sizes_index = @profile.sizes.order("created_at DESC").first(5)
    @sizes = Size.where(:user_id => @profile.user.id).order("mikor ASC").all

    @new_photo = @profile.photos.new
    @photos = @profile.photos.all
    #graphs
    #@testsuly = Size.where(:user_id => @profile.user.id).order("mikor ASC").collect(&:testsuly).compact
    #@testzsir = Size.where(:user_id => @profile.user.id).order("mikor ASC").collect(&:testzsir).compact
    @testzsir = []
    @testsuly = []
    @mikor_ts = []
    @mikor_tzs = []

    @profile.sizes.order("mikor ASC").each do |size|
      if size.testsuly.nil?
      else
        @testsuly << size.testsuly
        @mikor_ts << size.mikor
      end
    end

    @profile.sizes.order("mikor ASC").each do |size|
      if size.testzsir.nil?
      else
        @testzsir << size.testzsir
        @mikor_tzs << size.mikor
      end
    end

    @times = Size.where(:user_id => @profile.user.id).order("mikor ASC").collect(&:mikor).compact

    @ts = LazyHighCharts::HighChart.new('graph', :style => "height:240px;max-width:380px;" ) do |f|
      f.options[:chart][:defaultSeriesType] = "area"
      f.series(:name=>'Testsúly(kg)', :data=>@testsuly)
      #f.series(:name=>'Testzsír(%)', :data=>@testzsir, :visible => false, opposite: true)
      #f.xAxis(:categories => ["United States", "Japan", "China", "Germany", "France"])
      f.xAxis(:categories => @mikor_ts )
      #f.xAxis(:categories => @mikor_tzs, :visible => false, opposite: true )
    end

    #@tzs = LazyHighCharts::HighChart.new('graph', :style => "height:230px;max-width:380px;" ) do |f|
    #  f.options[:chart][:defaultSeriesType] = "area"
    #  f.series(:name=>'Testzsír(%)', :data=>@testzsir)
    #  f.xAxis(:categories => @mikor_tzs )
    #end

    #workout calendar
    @workout = @profile.workouts.order('mikor ASC').last
    @workouts = @profile.workouts.all
    @workouts_by_date = @workouts.group_by(&:mikor_date)
    # @date = params[:date] ? Date.parse(params[:date]) : Date.today # Ez mire jó?
    if params[:date]
      @year = params[:date].to_date.year
      @month = params[:date].to_date.month 
    else
      @year = Date.today.year
      @month = Date.today.month
    end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @profile, notice: 'Profilod sikeresen frissítetted.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @profile = Profile.find(params[:id])
    @user = User.find_by_id(@profile.user_id)
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_path, notice: 'Profil törölve.' }
      format.json { head :no_content }
    end
  end

  def following
    @title = "Following"
    @profile = Profile.find(params[:id])
    @profiles = @profile.followed_profiles
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @profile = Profile.find(params[:id])
    @profiles = @profile.followers
    render 'show_follow'
  end

  #def image
  #  @profile = Profile.find(params[:id])
  #  send_file "#{Rails.root}/tmp/uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}",:disposition => 'inline', :type=>"application/jpg", :x_sendfile=>true
  #end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def myprofile?(profile)
  	if profile.private
  	  if user_signed_in?
  	  	if profile.user_id == current_user.id
  	  		true
  	    end
  	  end
  	else
  	  true
  	end
  end
end

app/views/profiles/_chart.html.haml
#chart.standard
  %strong 
    Testsúly grafikon.
  %br/
  %br/
  = high_chart("chart_ts", @ts)

app/views/profiles/_clearing.html.haml
#photos
  %ul.clearing-thumbs{"data-clearing" => ""}
    - @profile.photos.each do |photo|
      - if photo.image_url
        %li
          = link_to photo.image_url do
            = image_tag(photo.image_url(:thumb), class: "th")

%br/

app/views/profiles/_current_workout.html.haml
.row-fluid
  .span12
    %h5.muted.pagination-centered
      utolsó edzés
    %h4
      = @workout.name
    %p
      = simple_format(@workout.description)

app/views/profiles/_edzesterv.html.haml
%h4.muted
  Edzéstervem

app/views/profiles/_follow_form.html.haml
- if current_user
  - unless current_user.profile == @profile
    #follow-form
      - if current_user.profile.following?(@profile)
        = render 'profiles/unfollow'
      - else
        = render 'profiles/follow'

app/views/profiles/_modal_picture.html.haml
#myModal.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#myModalLabel Képfeltöltés
  .modal-body
    = simple_form_for([@profile, @new_photo], :html => { :class => 'form-horizontal' }) do |f|
      .form-inputs
        = f.input :name, label: "Kép neve"
        = f.input :image, label: "Képfájl"
        = f.input :keszult, label: "Készült"
        = f.input :description, label: "Leírás", :input_html => { rows: 3, class: "span10"}
        = f.input :testsuly, label: "Testsúly(kg)"
        = f.input :testzsir, label: "Testzsír(%)"
      .form-actions
        = f.submit "Feltöltés", class: "btn btn-primary btn-large"
        = link_to "Mégse", "#", class: "btn btn-large", "data-dismiss" => "modal", id: "close-size"

app/views/profiles/_nevjegy.html.haml
.opaque-wrap
  .standard.standard-header
    %strong.muted
      Névjegy
    - if can? :update, @profile
      .btn-group.pull-right.opaque
        %a.btn.btn-small.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
          %span.caret
        %ul.dropdown-menu
          %li
            = link_to edit_profile_path(@profile) do
              %i.icon-pencil
              Szerkesztés
  .standard.personal
    %table.table-condensed
      %tbody
        %tr
          %td Név
          %td= @profile.real_name
        %tr
          %td Szül.
          %td= @profile.date_of_birth
        %tr
          %td Város
          %td= @profile.varos
        %tr
          %td Edzőterem
          %td= @profile.gym
        %tr
          %td Nem
          %td= @profile.nem2
        %tr
          %td Magasság
          %td= cm(@profile.magassag)
        %tr
          %td Sportág
          %td= @profile.sport

app/views/profiles/_orbit.html.haml
%ul{"data-orbit" => ""}
  = @photos.each do |photo|
    - if photo.image_url
      %li
        = image_tag(photo.image_url)

app/views/profiles/_pictures.html.haml
%br/
.opaque-wrap
  .standard.standard-header
    %strong.muted  Képek
    .right
      - if can? :update, @profile
        = link_to "#myModal", "data-toggle" => "modal", title: "Új kép hozzáadása", class: "opaque" do
          Új kép
  .standard
    .pictures
      - if @photos.any?
        - @photos.each do |photo|
          = link_to profile_photos_path(@profile) do
            = image_tag(photo.image_url(:thumb), class: "photo-thumb", title: photo.name) if photo.image_url
      - else
        %strong.pagination-centered.muted Tölts fel képeket.

app/views/profiles/_private.html.haml
.row-fluid
  .span12
    %h2.text-warning.pagination-centered Privát profil.

app/views/profiles/_profile_nav.html.haml
.row
  .small-11.small-centered.columns
    .row
      .small-6.columns
        %h2.profile-header
          = link_to @profile.user_name, @profile if @profile.user_name
.row
  .small-11.small-centered.columns
    .cover-wrapper
      = image_tag(@profile.cover_image_url(:cover), class: "cover-image") if @profile.cover_image_url
    - if @profile.image_url
      = image_tag(@profile.image_url(:thumb), class: "th profile-img")
    - else
      = image_tag('user.png', class: "th profile-img")
.row
  .small-11.small-centered.columns
    .row
      .small-6.small-offset-6.columns
        %ul.small-block-grid-4
          %li
            %h6
              = link_to following_profile_path(@profile) do
                = @profile.followed_profiles.count
                követés
          %li
            %h6
              = link_to followers_profile_path(@profile) do
                = @profile.followers.count
                követő
          %li
            %h6
              Ts:
              = kg(last_valid(:testsuly))
          %li
            %h6
              Tzs:
              = pc(last_valid(:testzsir))

/- if @profile && @no_nav == nil
/  .row-fluid
/    .span12
/      .profile-nav
/        .row-fluid
/          .span6
/            %h1
/              = link_to @profile.user_name , @profile if @profile.user_name
/.row-fluid
/  .span12.cover-image
/    = image_tag(@profile.cover_image_url(:cover)) if @profile.cover_image_url
/    - if @profile.image_url
/      = image_tag(@profile.image_url(:thumb), class: "profile-img img-polaroid")
/    - else
/      = image_tag('user.png', class: "profile-img img-polaroid")
/.row-fluid
/  .span12
/    %ul.nav.nav-tabs.ul-profile-nav2
/      %li{:class => "#{"active" if current_page?(@profile)}", id: "profile-link"}
/        = link_to "Profil", @profile
/      %li{:class => "#{"active" if current_page?(profile_photos_path(@profile))}", id: "photos-link"}
/        = link_to "Fényképek", profile_photos_path(@profile)
/      %li.pull-right
/        = render "profiles/follow_form"
/      %li.pull-right
/        = link_to following_profile_path(@profile) do
/          = @profile.followed_profiles.count
/          követés
/      %li.pull-right
/        = link_to followers_profile_path(@profile) do
/          = @profile.followers.count
/          követő

app/views/profiles/_sizes.html.haml
%br/
%table.table
  %tbody
    %tr
      %td
        %h5 Testsúly
      %td
        %h5= kg(last_valid(:testsuly))
    %tr
      %td
        %h5 Testzsír
      %td
        %h5= pc(last_valid(:testzsir))
    %tr
    %tr
      %td
        %h5 Nyak
      %td
        %h5= cm(last_valid(:nyak))
    %tr
      %td
        %h5 Mell
      %td
        %h5= cm(last_valid(:mell))
    %tr
      %td
        %h5 Váll
      %td
        %h5= cm(last_valid(:vall))
    %tr
      %td
        %h5 Kar
      %td
        %h5= cm(last_valid(:kar))
    %tr
      %td
        %h5 Alkar
      %td
        %h5= cm(last_valid(:alkar))
    %tr
      %td
        %h5 Derék
      %td
        %h5= cm(last_valid(:derek))
    %tr
      %td
        %h5 Csípő
      %td
        %h5= cm(last_valid(:csipo))
    %tr
      %td
        %h5 Comb
      %td
        %h5= cm(last_valid(:comb))
    %tr
      %td
        %h5 Vádli
      %td
        %h5= cm(last_valid(:vadli))

app/views/profiles/index.html.haml
.row-fluid
  .span8.offset2
    - @profiles.each do |profile|
      .row-fluid.profile-search.standard
        .span2
          = link_to profile do
            - if profile.image_url
              = image_tag(profile.image_url(:thumb), class: "img-polaroid")
            - else
              = image_tag('user.png', class: "img-polaroid")
        .span8.search-index-name
          = link_to profile do
            %h4
              = profile.user_name
          %span.label{ title: "Testsúly"}
            TS
          = kg(last_valid_profile(profile, :testsuly))
          %span.label{ title: "Testsúly"}
            TZS
          = pc(last_valid_profile(profile, :testzsir))
          %br/
          %br/
          %span.label.label-info
            = profile.followers.count
          Követő

app/views/profiles/show_follow.html.haml
g