config/routes.rb
Anabol::Application.routes.draw do

  resources :versions,  :path => "/verziok"#, :only => [:edit, :update, :index, :new, :creae],
  resources :meta_reports

  devise_scope :user do
    get '/felhasznalok/auth/:provider' => 'users/omniauth_callbacks#passthru'
    get "/belepes" => "devise/sessions#new"
    get "/regisztracio" => "devise/registrations#new"
    match "/kilepes" => "devise/sessions#destroy"
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/meta", to: "static_pages#meta"
  get "/adatvedelem", to: "static_pages#adatvedelem"
  get "/feltetelek", to: "static_pages#feltetelek"
  get "/users", to: "static_pages#users"

  Inboxes::Engine.routes.draw do
    resources :discussions, :except => :edit, :module => :inboxes do
      resources :messages, :only => [:create, :index]
      resources :speakers, :only => [:create, :destroy]
      member do
        post 'leave'
      end
    end
  end

  resources :relationships, only: [:create, :destroy]
  root :to => "static_pages#home"

  get 'kereses' => 'profiles#index'

  resources :profiles, :only => [:show, :edit, :update, :destroy, :index], :path => "/profil" do
     resources :sizes, :path => "meres"
     resources :workouts, :path => "edzes"
     resources :photos, :path => "kepek"
    member do
      get :following, :followers
    end
  end

end

app/models/workout.rb
class Workout < ActiveRecord::Base
  attr_accessible :description, :mikor, :user_id, :template, :name, :period_time, :mikor_date, :color
  
  validates :mikor, :name, :presence => true
  validates_uniqueness_of :slug
  
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :profile

  before_save :setmydate

  def setmydate
  	self.mikor_date = self.mikor.to_date if self.mikor
  end

end

app/controllers/workouts_controller.rb
# coding: utf-8
class WorkoutsController < ApplicationController

  before_filter :get_profile
  
  load_and_authorize_resource

  #def index
  #  @workouts = @profile.workouts.all
  #  respond_to do |format|
  #    format.html # index.html.erb
  #    format.json { render json: @workouts }
  #  end
  #end

  def get_profile
    @profile = Profile.find(params[:profile_id])
  end

  def new
    @workout = @profile.workouts.new
  end

  def show
    @workout = @profile.workouts.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.js {}
      format.json { render json: @workout }
    end
  end


  def edit
    @workout = @profile.workouts.find(params[:id])
  end


  def create
    @workout = @profile.workouts.new(params[:workout])
    #@workout.user_id = current_user.id
    respond_to do |format|
      if @workout.save
        format.html { redirect_to root_path, notice: 'Edzés sikeresen létrehozva.' }
        format.json { render json: @workout, status: :created, location: @workout }
      else
        format.html { render action: "new" }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @workout = @profile.workouts.find(params[:id])

    respond_to do |format|
      if @workout.update_attributes(params[:workout])
        format.html { redirect_to root_path, notice: 'Edzés sikeresen frissítve.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout = Workout.find(params[:id])
    @workout.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Edzés törölve.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.haml
#wf
  .row
    .small-8.small-offset-2
      = simple_form_for([@profile, @workout], :html => { :class => 'form-horizontal' }) do |f|
        = f.error_notification
      
        .form-inputs
          = f.input :name, required: true, label: "Edzés neve"
          .datetime.input-append
            = f.input :mikor, required: true, :label => "Edzés ideje ÉÉÉÉ/HH/NN ÓÓ:PP formátumba add meg. pl.: 2013/08/17 15:30", :wrapper => :append do
              = f.input_field :mikor, :as => :string, "data-format" => "yyyy/MM/dd hh:mm:ss" 
          = f.input :period_time, label: "Időtartam - percben"
          .row-fluid
            .span3
              = f.input :color, priority: "fehér", collection: [ "fehér", "kék"], label: "Jelölőszín", as: :radio_buttons
          /= f.input :template, label: "Mentés sablonként"
          = f.input :description, label: "Edzés leírása", input_html: { class: 'span10' }
      
        .form-actions
          = f.button :submit, "Mentés", class: "button"
          = link_to "Mégse", "#", class: "button secondary", id: "close-workout"

app/views/workouts/_showme.html.haml
- if @workout
  #showme.standard
    %strong
      = @workout.name
      %small
        = localize(@workout.mikor, :format => :short) if @workout.mikor
      /= link_to edit_profile_workout_path(@profile, @workout) do
      /  %i.icon-pencil
      - if can? :update, @workout
        .right
          %a.button.tiny.secondary.dropdown{"data-dropdown" => "drop1", :href => "#"}
            %i.fi-widget
          %ul.f-dropdown#drop1
            %li
              = link_to new_profile_workout_path(@profile, @workout) do
                %i.fi-plus
                Új edzés
            %li
              = link_to edit_profile_workout_path(@profile, @workout) do
                %i.fi-page-edit
                Szerkesztés
            %li
              = link_to profile_workout_path(@profile, @workout), method: :delete, :data => { :confirm => 'Biztos vagy benne, hogy törlöd?' } do
                %i.fi-trash
                Törlés
    %p
      Időtartam:
      - if @workout.period_time
        = @workout.period_time.to_s + " perc" 
      - else
        = "--"
    %p
      #workout-description
        %small
          = simple_format(@workout.description)



/%a.button.dropdown{"data-dropdown" => "drop1", :href => "#"} Dropdown Button
/%br/
/%ul#drop1.f-dropdown
/  %li
/    %a{:href => "#"} This is a link
/  %li
/    %a{:href => "#"} This is another
/  %li
/    %a{:href => "#"} Yet another

app/views/workouts/edit.html.haml
%h2.text-center
  = @workout.name
  Edzés szerkesztése

= render 'form'

app/views/workouts/index.html.haml
- provide(:title, "Edzéseim")
%h2 Edzések listája

%table.table
  %tr
    %th Description
    %th Mikor
    %th User
    %th
    %th
    %th

  - @workouts.each do |workout|
    %tr
      %td= workout.description
      %td= workout.mikor
      %td= workout.user_id
      %td= link_to 'Show', profile_workout_path(@profile, workout)
      %td= link_to 'Edit', edit_profile_workout_path(@profile, workout)
      %td= link_to 'Destroy', profile_workout_path(@profile, workout), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Workout', new_profile_workout_path(@profile)

app/views/workouts/new.html.haml
- provide(:title, "Új edzés")
%h2.text-center
  Új edzés
= render "workouts/form"

app/views/workouts/new.js.erb
//$('#size-form').fadeOut("fast");
//$('#wf').remove();
//$('#sf').remove();
//$('#workout-form').fadeIn("fast").append('<%= j render "form" %>');
//$('#yield').fadeOut("fast");
//$('#close-workout').on('click', function() {
//  $('#wf').remove();
//  $('#sf').remove();
//  $('#workout-form').fadeOut("fast");
//  $('#yield').fadeIn("fast");
//});
//$(".datetime").datetimepicker()

app/views/workouts/show.html.haml
%p
  %b Description:
  = @workout.description
%p
  %b Mikor:
  = @workout.mikor

/= link_to 'Edit', edit_workout_path(@workout)
/= link_to 'Back', workouts_path
/= link_to 'Delete', @workout, :method => :delete

app/views/workouts/show.js.erb
$("#showme").fadeOut('fast', function() {
  $('#showme').remove();
  $(".workout-wrapper").append("<%= j render('showme') %>");
  $("#showme").fadeIn('fast');
});