config/routes.rb
Anabol::Application.routes.draw do

  resources :versions,  :path => "/verziok"#, :only => [:edit, :update, :index, :new, :creae],
  resources :meta_reports

  devise_scope :user do
    get '/felhasznalok/auth/:provider' => 'users/omniauth_callbacks#passthru'
    get "/belepes" => "devise/sessions#new"
    get "/regisztracio" => "devise/registrations#new"
    match "/kilepes" => "devise/sessions#destroy"
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/meta", to: "static_pages#meta"
  get "/adatvedelem", to: "static_pages#adatvedelem"
  get "/feltetelek", to: "static_pages#feltetelek"
  get "/users", to: "static_pages#users"

  Inboxes::Engine.routes.draw do
    resources :discussions, :except => :edit, :module => :inboxes do
      resources :messages, :only => [:create, :index]
      resources :speakers, :only => [:create, :destroy]
      member do
        post 'leave'
      end
    end
  end

  resources :relationships, only: [:create, :destroy]
  root :to => "static_pages#home"

  get 'kereses' => 'profiles#index'

  resources :profiles, :only => [:show, :edit, :update, :destroy, :index], :path => "/profil" do
     resources :sizes, :path => "meres"
     resources :workouts, :path => "edzes"
     resources :photos, :path => "kepek"
    member do
      get :following, :followers
    end
  end

end

app/models/meta_report.rb
class MetaReport < ActiveRecord::Base
  attr_accessible :description, :name, :image

  belongs_to :profile

  mount_uploader :image, ImageUploader
end

app/controllers/meta_reports_controller.rb
# coding: utf-8
class MetaReportsController < ApplicationController
  load_and_authorize_resource

  before_filter :get_user

  def index
    @meta_reports = MetaReport.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meta_reports }
    end
  end

  # GET /meta_reports/1
  # GET /meta_reports/1.json
  def show
    @meta_report = MetaReport.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meta_report }
    end
  end

  # GET /meta_reports/new
  # GET /meta_reports/new.json
  def new
    @meta_report = @profile.meta_reports.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meta_report }
    end
  end

  # GET /meta_reports/1/edit
  def edit
    @meta_report = MetaReport.find(params[:id])
  end

  # POST /meta_reports
  # POST /meta_reports.json
  def create
    @meta_report = @profile.meta_reports.new(params[:meta_report])

    respond_to do |format|
      if @meta_report.save
        format.html { redirect_to root_path, notice: 'Jelentés sikeresen létrehozva.' }
        format.json { render json: @meta_report, status: :created, location: @meta_report }
      else
        format.html { redirect_to meta_path }
        format.json { render json: @meta_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meta_reports/1
  # PUT /meta_reports/1.json
  def update
    @meta_report = MetaReport.find(params[:id])

    respond_to do |format|
      if @meta_report.update_attributes(params[:meta_report])
        format.html { redirect_to @meta_report, notice: 'Jelentés frissítve.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meta_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meta_reports/1
  # DELETE /meta_reports/1.json
  def destroy
    @meta_report = MetaReport.find(params[:id])
    @meta_report.destroy

    respond_to do |format|
      format.html { redirect_to meta_reports_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/meta_reports_helper.rb
module MetaReportsHelper
end

app/views/meta_reports/_form.html.haml
= simple_form_for(@meta_report) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description

  .form-actions
    = f.button :submit

app/views/meta_reports/edit.html.haml
%h1 Editing meta_report

= render 'form'

= link_to 'Show', @meta_report
\|
= link_to 'Back', meta_reports_path

app/views/meta_reports/index.html.haml
%h2.muted
  Meta reports

- @meta_reports.each do |meta|
  .row-fluid.standard
    .span2.standard
      = link_to Profile.find(meta.profile_id) do
        = Profile.find(meta.profile_id).user_name
      = meta.name
    .span8
      = meta.description
    .span2
      - if can? :edit, Version
        = link_to edit_version_path(meta) do
          %i.icon-edit
        = link_to meta, :method => :delete do
          %i.icon-trash

app/views/meta_reports/new.html.haml
%h1 New meta_report

= render 'form'

= link_to 'Back', meta_reports_path

app/views/meta_reports/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @meta_report.name
%p
  %b Description:
  = @meta_report.description

= link_to 'Edit', edit_meta_report_path(@meta_report)
\|
= link_to 'Back', meta_reports_path