config/routes.rb
Anabol::Application.routes.draw do

  resources :versions,  :path => "/verziok"#, :only => [:edit, :update, :index, :new, :creae],
  resources :meta_reports

  devise_scope :user do
    get '/felhasznalok/auth/:provider' => 'users/omniauth_callbacks#passthru'
    get "/belepes" => "devise/sessions#new"
    get "/regisztracio" => "devise/registrations#new"
    match "/kilepes" => "devise/sessions#destroy"
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/meta", to: "static_pages#meta"
  get "/adatvedelem", to: "static_pages#adatvedelem"
  get "/feltetelek", to: "static_pages#feltetelek"
  get "/users", to: "static_pages#users"

  Inboxes::Engine.routes.draw do
    resources :discussions, :except => :edit, :module => :inboxes do
      resources :messages, :only => [:create, :index]
      resources :speakers, :only => [:create, :destroy]
      member do
        post 'leave'
      end
    end
  end

  resources :relationships, only: [:create, :destroy]
  root :to => "static_pages#home"

  get 'kereses' => 'profiles#index'

  resources :profiles, :only => [:show, :edit, :update, :destroy, :index], :path => "/profil" do
     resources :sizes, :path => "meres"
     resources :workouts, :path => "edzes"
     resources :photos, :path => "kepek"
    member do
      get :following, :followers
    end
  end

end

app/views/layouts/_footer.html.haml
.row-fluid
  .span3
    %br/
    %p.muted
      Anabolizmus.com
      = link_to versions_path, class: "text-info" do
        - if @version.v
          = @version.v
        - elsif @version.name
          = truncate(@version.name, length: 10)
  .span3.offset6
    %br/
    /%ul.unstyled
    /  %li
    /    = link_to "Adatvédelmi nyilatkozat", adatvedelem_path
    /  %li
    /    = link_to "Felhasználási feltételek", feltetelek_path

app/views/layouts/_login_modal.html.haml
#login-modal.reveal-modal
  .row
    .small-12.columns
      .row
        .small-10.small-centered.columns
          %h2 Belépés
          = simple_form_for("user", :url => user_session_path) do |f|
            = f.input :email, label: false, placeholder: "email"
            = f.input :password, label: false, placeholder: "jelszó"
            .form-actions
              = f.submit 'Belépés', class: "button expand"
              = link_to user_omniauth_authorize_path(:facebook) do
                .button.button-facebook.expand
                  %i.social.foundicon-facebook
                  Belépés Facebokkal
  %a.close-reveal-modal x

app/views/layouts/_nav.html.haml
.contain-to-grid
  %nav.top-bar{:data => {"custom_back_text" => "true", "back-text" => "lol"}}
    %ul.title-area
      / Title Area
      %li.name
        %h1
          = link_to "Anabolizmus", root_path
      / Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
      %li.toggle-topbar.menu-icon
        %a{:href => "#"}
    %section.top-bar-section
      / Left Nav Section
      %ul.left
        - if user_signed_in?
          %li.divider
          %li{ class: "#{"active" if current_page?(meta_path)}" }
            = link_to "Meta", meta_path
        - if user_signed_in?
          %li.divider
          %li.has-form
            = form_tag kereses_path, method: :get do
              = text_field_tag :query, params[:query], placeholder: "Keresés"
      / Right Nav Section
      %ul.right
        - unless user_signed_in?
          %li.has-form
            = link_to regisztracio_path, class: "button success" do
              Regisztráció
          %li.has-form
            %a{"data-reveal-id" => "login-modal", :href => "#", class: "button "}
              Belépés
        - if user_signed_in?
          %li{ class: "#{'active' if current_page?(new_profile_workout_path(current_user.profile))}"}
            = link_to new_profile_workout_path(current_user.profile) do
              Új edzés
          %li.divider
          %li{ class: "#{'active' if current_page?(new_profile_size_path(current_user.profile))}"}
            = link_to new_profile_size_path(current_user.profile) do
              Új mérés
          %li.divider
          %li{ class: "#{"active" if current_page?(discussions_url)}" }
            = link_to discussions_url, class: "fix-height" do
              %i.fi-mail
          %li.divider
          %li.has-dropdown
            %a{:href => "#"} Menu
            %ul.dropdown
              %li{ class: "#{'active' if current_page?(profile_path(current_user.profile))}"}
                = link_to profile_path(current_user.profile) do
                  Profilom
              %li{ class: "#{'active' if current_page?(edit_profile_path(current_user.profile))}"}
                = link_to edit_profile_path(current_user.profile) do
                  %i.fi-widget
                  Beállítások
              %li{ class: "#{'active' if current_page?(profile_sizes_path(current_user.profile))}"}
                = link_to profile_sizes_path(current_user.profile) do
                  Méréseim
              %li.divider
              %li
                = link_to "Kilépés", kilepes_path

- unless user_signed_in?
  = render 'layouts/login_modal'

/%li.divider.hide-for-small
/%li.has-dropdown
/  %a{:href => "#"} Main Item 4
/  %ul.dropdown
/    %li
/      %label Dropdown Level 1 Label
/    %li.has-dropdown
/      %a{:href => "#"} Dropdown Level 1a
/      %ul.dropdown
/        %li
/          %a{:href => "#"} Dropdown Level 2a
/        %li
/          %a{:href => "#"} Dropdown Level 2b
/        %li.has-dropdown
/          %a{:href => "#"} Dropdown Level 2c
/          %ul.dropdown
/            %li
/              %a{:href => "#"} Dropdown Level 3a
/            %li
/              %a{:href => "#"} Dropdown Level 3b
/            %li
/              %a{:href => "#"} Dropdown Level 3c
/        %li
/          %a{:href => "#"} Dropdown Level 2d
/        %li
/          %a{:href => "#"} Dropdown Level 2e
/        %li
/          %a{:href => "#"} Dropdown Level 2f
/    %li
/      %a{:href => "#"} Dropdown Level 1b
/    %li
/      %a{:href => "#"} Dropdown Level 1c
/    %li.divider
/    %li
/      %label Dropdown Level 1 Label
/    %li
/      %a{:href => "#"} Dropdown Level 1d
/    %li
/      %a{:href => "#"} Dropdown Level 1e
/    %li
/      %a{:href => "#"} Dropdown Level 1f
/    %li.divider
/    %li
/      %a{:href => "#"} See all →
/%li.divider
/%li.has-form
/%li.divider.show-for-small
/%li.has-form
/  %a.button{:href => "#"} Button!

app/views/layouts/application.html.haml
!!!
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class="ie6" lang="en">
/[if IE 7 ] <html class="ie7" lang="en">
/[if IE 8 ] <html class="ie8" lang="en">
/ [if (gte IE 9)|!(IE)]><!
%html{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    / Uncomment to make IE8 render like IE7
    / <meta http-equiv="X-UA-Compatible" content="IE=7" />
    / Set the viewport width to device width for mobile
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) + " - Anabolizmus" : "Anabolizmus"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = javascript_include_tag "vendor/custom.modernizr"
    = csrf_meta_tags
  %body{:class => @home_page ? 'homepage' : ''}
    = render "layouts/nav"
    .container
      .row
        .twelve.columns
          = display_flash_messages
    = yield

app/views/layouts/old_nav.html.haml
%header.navbar.navbar-fixed-top
  %nav.navbar-inner.navbar-custom
    .container
      / .btn-navbar is used as the toggle for collapsed navbar content
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      / Be sure to leave the brand out there if you want it shown
      = link_to  'Anabolizmus', root_path, class: "brand"
      / Everything you want hidden at 940px or less, place within here
      .nav-collapse.collapse
        %ul.nav.pull-left
          - if user_signed_in?
            %li
              = link_to "Meta", meta_path
        - if user_signed_in?
          = form_tag kereses_path, class: "navbar-form pull-left", method: :get do
            = text_field_tag :query, params[:query]
            %button.btn{:type => "submit"}
              %i.icon-search
        %ul.nav.pull-right
          - unless user_signed_in?
            %li{:class => "#{'active' if current_page?(regisztracio_path)}"}
              = link_to "Regisztráció", regisztracio_path
            %li{:class => "#{'active' if current_page?(new_user_session_path)}", id: "login-link"}
              = link_to "Belépés", "#"
          - else
            %li{:class => "#{'active' if current_page?(new_profile_workout_path(current_user.profile))}"}
              = link_to "Új edzés", new_profile_workout_path(current_user.profile), id: "new-workout", class: "btn-link"
            %li{:class => "#{'active' if current_page?(new_profile_size_path(current_user.profile))}"}
              = link_to "Új mérés", new_profile_size_path(current_user.profile), id: "new-size", class: "btn-link"
            %li{:class => "#{'active' if current_page?(discussions_path)}"}
              = link_to discussions_path do
                - if current_user.discussions.order("updated_at Desc").first.unread_for?(current_user)
                  %span.badge.badge-important
                    %i.icon-envelope.icon-white
                -else
                  %i.icon-envelope
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                %i.icon-user
                - if User.find_by_id(current_user.id).name.blank? 
                  = current_user.profile.user_name
                - else
                  = User.find_by_id(current_user.id).name
              %ul.dropdown-menu{"aria-labelledby" => "dLabel", :role => "menu"}
                %li{:class => "#{'active' if current_page?(profile_path(current_user.profile))}"}
                  = link_to profile_path(current_user.profile) do
                    %i.icon-user
                    Profilom
                %li{:class => "#{'active' if current_page?(edit_profile_path(current_user.profile))}"}
                  = link_to edit_profile_path(current_user.profile) do
                    %i.icon-wrench
                    Beállítások
                %li.divider
                /%li 
                /  = link_to profile_workouts_path(current_user.profile) do
                /    %i.icon-tag
                /    Edzéseim
                %li{:class => "#{'active' if current_page?(profile_sizes_path(current_user.profile))}"}
                  = link_to profile_sizes_path(current_user.profile) do
                    %i.icon-resize-horizontal
                    Méréseim
                %li.divider
                %li{:class => "#{'active' if current_page?(kilepes_path)}"}
                  = link_to "Kijelentkezés", kilepes_path, method: :delete, class: "muted"
    .container#login-container
      #login-box
        /= form_tag user_session_path do
        /  %ul.unstyled
        /    %li{:placeholder => "email" }
        /      = text_field_tag 'user[email]'
        /    %li
        /      = password_field_tag 'user[password]'
        /    %li
        /      %button.btn.btn-primary Belépés
        /      = link_to "Elfelejtett jelszó?", new_password_path('user'), class: "btn btn-link"
        #facebook-login
          = link_to user_omniauth_authorize_path(:facebook) do
            %btn.btn.btn-link.btn-block
              = image_tag('face_login.png')
        = simple_form_for("user", :url => user_session_path) do |f|
          = f.input :email, label: false, placeholder: "email"
          = f.input :password, label: false, placeholder: "jelszó"
          = f.input :remember_me, input_html: { value: '1' }, inline_label: 'Emlékezz rám!', as: :boolean, label: false
          = link_to "Elfelejtett jelszó?", new_password_path('user'), class: "btn btn-link"
          = f.submit 'Belépés', class: "btn btn-primary"